//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyRapPhim
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScreening
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblScreening()
        {
            this.tblSchedules = new HashSet<tblSchedule>();
        }
    
        public string screening_name { get; set; }
        public byte genre_id { get; set; }
        public short studio_id { get; set; }
        public Nullable<System.DateTime> screening_start { get; set; }
        public Nullable<System.DateTime> screening_end { get; set; }
    
        public virtual tblGenre tblGenre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSchedule> tblSchedules { get; set; }
        public virtual tblStudio tblStudio { get; set; }
    }
}
