//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyRapPhim
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuditorium
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAuditorium()
        {
            this.tblSchedules = new HashSet<tblSchedule>();
        }
    
        public string auditorium_id { get; set; }
        public string center_id { get; set; }
        public short seat_count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSchedule> tblSchedules { get; set; }
        public virtual tblCenter tblCenter { get; set; }
    }
}
