//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyRapPhim
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCenter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCenter()
        {
            this.tblAuditoriums = new HashSet<tblAuditorium>();
        }
    
        public string center_id { get; set; }
        public string center_name { get; set; }
        public string center_address { get; set; }
        public string center_contact { get; set; }
        public short center_auditorium_count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAuditorium> tblAuditoriums { get; set; }
    }
}
